apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "pod-mutating.spring-boot.example.com"
  annotations:
    cert-manager.io/inject-ca-from: test/spring-boot-sample
webhooks:
  - name: "pod-mutating.spring-boot.example.com"
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["ingresses"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: "test"
        name: "spring-boot-sample"
        path: "/mutate"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5