apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "validating.spring-boot.example.com"
  annotations:
    cert-manager.io/inject-ca-from: default/spring-boot-sample
webhooks:
  - name: "validating.spring-boot.example.com"
    rules:
      - apiGroups:   ["networking.k8s.io"]
        apiVersions: ["v1"]
        operations:  ["*"]
        resources:   ["ingresses"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: "default"
        name: "spring-boot-sample"
        path: "/validate"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5